image: ubuntu:18.04

variables:
  BIN_NAME: main.out

before_script:
  - apt-get -y update

stages:
  - build
  - test
  - pages

build:
  stage: build
  script:
    - apt-get -y install gcc g++
    - g++ -o ${BIN_NAME} main.cpp
  artifacts:
    paths:
      - ${BIN_NAME}

test:
  stage: test
  script:
    - chmod +x test/test?.sh
    - test/test1.sh
    - test/test2.sh
    - test/test3.sh
    - test/test4.sh

pages:
  stage: pages
  script:
    - apt-get -y install doxygen
    - apt-get -y install graphviz
    - doxygen Doxyfile.cfg
    - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
